import express from "express";
import dotenv from "dotenv";
import session from "express-session";
import fs from "fs";
import crypto from "crypto";
dotenv.config();
const app=express(),PORT=process.env.PORT||3000,BASE_URL=process.env.BASE_URL||`http://127.0.0.1:${PORT}`;
const CLIENT=process.env.GITHUB_CLIENT_ID||"",SECRET=process.env.GITHUB_CLIENT_SECRET||"";
const GROUPS="./data/groups.json",COURSES="./data/courses.json",CONFIG="./teacher-config.json",ANALYTICS="./data/analytics.json";
app.use(express.json({limit:"4mb"}));app.use(express.static("public"));app.use(session({secret:process.env.SESSION_SECRET||"vaihda",resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:"lax",secure:false,maxAge:28800000}}));
const read=(p,f)=>{try{return JSON.parse(fs.readFileSync(p,"utf8"))}catch{return f}},write=(p,d)=>fs.writeFileSync(p,JSON.stringify(d,null,2),"utf8");
const authT=(req,res,next)=>req.session?.teacher?next():res.status(401).json({error:"Opettajan kirjautuminen vaaditaan."});
const authS=(req,res,next)=>req.session?.githubUser?.login?next():res.status(401).json({error:"GitHub-kirjautuminen vaaditaan."});
const b64=b=>b.toString("base64").replaceAll("+","-").replaceAll("/","_").replaceAll("=","");
const slug=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");
function findStudent(login){for(const g of read(GROUPS,{groups:[]}).groups||[])for(const s of g.students||[])if(String(s.githubUsername||"").toLowerCase()===String(login||"").toLowerCase())return{group:g,student:s};return null;}
function studentCourses(login){const m=findStudent(login);if(!m)return{matched:false,courses:[]};const courses=(read(COURSES,{courses:[]}).courses||[]).filter(c=>(c.groupIds||[]).includes(m.group.id)).map(c=>({...c,group:{id:m.group.id,name:m.group.name},student:{id:m.student.id,name:m.student.name,githubUsername:m.student.githubUsername}}));return{matched:true,group:m.group,student:m.student,courses};}
function repoUrl(a,s){return s?.githubUsername?`https://github.com/${s.githubUsername}/${slug(a.repoPrefix||a.name)}-${slug(s.githubUsername)}`:"";}
app.get('/auth/github',(req,res)=>{if(!CLIENT||!SECRET)return res.status(503).send('GitHub OAuth -asetuksia ei ole määritelty .env-tiedostoon.');const state=b64(crypto.randomBytes(24)),verifier=b64(crypto.randomBytes(48)),challenge=b64(crypto.createHash('sha256').update(verifier).digest());req.session.oauthState=state;req.session.pkceVerifier=verifier;const p=new URLSearchParams({client_id:CLIENT,redirect_uri:`${BASE_URL}/auth/github/callback`,state,code_challenge:challenge,code_challenge_method:'S256',prompt:'select_account'});res.redirect(`https://github.com/login/oauth/authorize?${p}`);});
app.get('/auth/github/callback',async(req,res)=>{try{const code=String(req.query.code||''),state=String(req.query.state||'');if(!code||state!==req.session.oauthState)throw Error('OAuth state -tarkistus epäonnistui.');const verifier=req.session.pkceVerifier;delete req.session.oauthState;delete req.session.pkceVerifier;const tr=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({client_id:CLIENT,client_secret:SECRET,code,redirect_uri:`${BASE_URL}/auth/github/callback`,code_verifier:verifier})});const td=await tr.json();if(!td.access_token)throw Error(td.error_description||'Tokenin haku epäonnistui.');const ur=await fetch('https://api.github.com/user',{headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${td.access_token}`,'X-GitHub-Api-Version':'2026-03-10','User-Agent':'Koodiopas-v12'}});const u=await ur.json();if(!u.login)throw Error('GitHub-käyttäjää ei saatu.');req.session.githubUser={id:u.id,login:u.login,name:u.name||'',avatarUrl:u.avatar_url||''};res.redirect('/?github_login=ok');}catch(e){res.redirect('/?github_login=error&message='+encodeURIComponent(e.message));}});
app.post('/api/student/logout',(req,res)=>{delete req.session.githubUser;res.json({ok:true});});
app.get('/api/student/session',(req,res)=>{const u=req.session?.githubUser;if(!u)return res.json({authenticated:false});const m=studentCourses(u.login);res.json({authenticated:true,githubUser:u,matched:m.matched,student:m.student||null,group:m.group||null});});
app.get('/api/student/courses',authS,(req,res)=>res.json(studentCourses(req.session.githubUser.login)));
app.get('/api/student/repo',authS,(req,res)=>{const m=studentCourses(req.session.githubUser.login),c=m.courses.find(x=>x.id===String(req.query.courseId||'')),a=c?.assignments?.find(x=>x.id===String(req.query.assignmentId||''));if(!m.matched)return res.status(403).json({error:'GitHub-tunnusta ei ole liitetty opiskelijaan.'});if(!c||!a)return res.status(404).json({error:'Tehtävää ei löytynyt.'});res.json({repoUrl:repoUrl(a,m.student),course:c,assignment:a});});
app.post('/api/teacher/login',(req,res)=>{const p=String(req.body?.password||''),c=process.env.TEACHER_PASSWORD;if(!c||c==='vaihda_tahan_vahva_salasana')return res.status(503).json({error:'Määritä TEACHER_PASSWORD .env-tiedostoon.'});if(p!==c)return res.status(401).json({error:'Väärä salasana.'});req.session.teacher=true;res.json({ok:true});});
app.post('/api/teacher/logout',(req,res)=>{delete req.session.teacher;res.json({ok:true});});app.get('/api/teacher/session',(req,res)=>res.json({authenticated:req.session?.teacher===true}));
app.get('/api/config/public',(req,res)=>res.json({teacherMessage:read(CONFIG,{}).teacherMessage||''}));
app.get('/api/groups',authT,(req,res)=>res.json(read(GROUPS,{groups:[]})));app.put('/api/groups',authT,(req,res)=>{const groups=Array.isArray(req.body?.groups)?req.body.groups:[];write(GROUPS,{groups});res.json({ok:true,groups});});
app.get('/api/courses',authT,(req,res)=>res.json(read(COURSES,{courses:[]})));app.put('/api/courses',authT,(req,res)=>{const courses=Array.isArray(req.body?.courses)?req.body.courses:[];write(COURSES,{courses});res.json({ok:true,courses});});
app.get('/api/repo-plan',authT,(req,res)=>{const groups=read(GROUPS,{groups:[]}).groups||[],courses=read(COURSES,{courses:[]}).courses||[],rows=[];for(const c of courses)for(const a of c.assignments||[])for(const gid of c.groupIds||[]){const g=groups.find(x=>x.id===gid);if(!g)continue;for(const s of g.students||[])rows.push({course:c.name,assignment:a.name,group:g.name,student:s.name||s.id,githubUsername:s.githubUsername||'',repoUrl:repoUrl(a,s)});}res.json({rows});});
app.post('/api/analyze',authS,(req,res)=>{const m=studentCourses(req.session.githubUser.login),c=m.courses.find(x=>x.id===req.body?.courseId),a=c?.assignments?.find(x=>x.id===req.body?.assignmentId);if(!m.matched)return res.status(403).json({error:'GitHub-tunnusta ei ole liitetty opiskelijaan.'});if(!c||!a)return res.status(404).json({error:'Tehtävää ei löytynyt.'});const d=read(ANALYTICS,{events:[]});d.events.push({id:crypto.randomUUID(),timestamp:new Date().toISOString(),githubUsername:req.session.githubUser.login,studentId:m.student.id,studentName:m.student.name,groupId:m.group.id,groupName:m.group.name,courseId:c.id,courseName:c.name,assignmentId:a.id,assignmentName:a.name,message:String(req.body?.message||'').slice(0,500),demo:true});write(ANALYTICS,d);res.status(503).json({demo:true,error:'GitHub-kirjautuminen ja opiskelijan tunnistaminen toimivat. Tekoäly kytketään myöhemmin.'});});
app.listen(PORT,()=>console.log(`Koodiopas v12: ${BASE_URL}`));
